name: Burger Express Dev Deployment
on:
  workflow_run:
    workflows: ["Backend Build and Check"]
    branches:
      - development
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Backend Artefakt
        uses: actions/download-artifact@v4
        with:
          name: app-jar      # so hast du das Artefakt beim Build benannt
          path: backend/target/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .                           # verweist auf dein Dockerfile
          push: true                          # damit das Image hochgeladen wird
          tags: ${{ secrets.DOCKER_IMAGE_TAG }}

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: push-to-docker-hub

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
